import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
// https://dev.to/sabbirsobhani/how-to-dynamically-change-favicon-icon-in-nextjs-14-a-step-by-step-guide-26l1
// https://assets.berty.tech/files/favicon_berty--1_android-chrome-512x512_hu8c11226219fbafadc0690fa2ac23a909_19505_512x0_resize_box_2.png
export const metadata: Metadata = {
  title: 'Next 14 TailWind',
  description: 'Generated by create next app',
  // icons: {
  //   icon: ['/favicon.ico?v=4'],
  //   apple: ['/favicon.ico?v=4'],
  //   shortcut: ['/favicon.ico']
  // },
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}
